#!/bin/sh
# Block commits that contain TODO

git diff --cached --name-only | ForEach-Object {
    if (Select-String -Path $_ -Pattern "TODO" -Quiet) {
        Write-Host " Commit blocked: Remove TODO comments"
        exit 1
    }
}
exit 0
